apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo-app
  template:
    metadata:
      labels:
        app: devops-demo-app
    spec:
      containers:
        - name: devops-demo-app
          image: devopsdemoacricefrb.azurecr.io/devops-app:v1
          ports:
            - containerPort: 8080
