name: Deploy to Azure AKS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      ACR_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      IMAGE_NAME: devops-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ⬇⬇ old azure/docker-login काढून टाकून हा step ठेव
      - name: Login to ACR via Azure CLI
        run: az acr login --name devopsdemoacrye5c0e

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image
        run: |
          cd app
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:v${{ github.run_number }} \
            --push \
            .

      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: devopsdemo-rg
          cluster-name: devopsdemo-aks

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.0

      - name: Deploy to AKS using Helm
        run: |
          helm upgrade --install devops-demo-app ./helm/devops-demo-app \
            --namespace default \
            --set image.repository=$ACR_LOGIN_SERVER/$IMAGE_NAME \
            --set image.tag=v${{ github.run_number }}
          kubectl rollout status deployment/devops-demo-app -n default









